module Geometry.Curve exposing (Arc, Curve(..), from, to, shiftFrom, shiftTo, point, middle)

import Geometry.Point as Point exposing (Point)
import Geometry.QuadraticBezier as Bez exposing (QuadraticBezier)

type alias Arc = {from : Point, to : Point, r : Float, center : Point }

type Curve = CurveBezier QuadraticBezier | CurveArc Arc

from : Curve -> Point
from c =
    case c of
        CurveBezier q -> q.from
        CurveArc a -> a.from

to : Curve -> Point
to c =
    case c of
        CurveBezier q -> q.to
        CurveArc a -> a.to

shiftFrom : Curve -> Float -> Point
shiftFrom c shift =
    case c of
        CurveBezier q -> Bez.shiftFrom q shift
        CurveArc a -> 
            -- todo 
            Point.towardsBentDiagonal a.from (Point.middle a.from a.to) a.center shift

shiftTo : Curve -> Float -> Point
shiftTo c shift =
    case c of
        CurveBezier q -> Bez.shiftTo q shift
        CurveArc a -> 
            -- todo
            Point.towardsBentDiagonal a.to (Point.middle a.from a.to) a.center shift


point : Curve -> Float -> Point
point q t =
    case q of
        CurveBezier b -> Bez.point b t
        CurveArc a -> 
            -- untested (generated by copilot)
            let angleFrom = Point.pointToAngle <| Point.subtract a.center a.from in
            let angleTo = Point.pointToAngle <| Point.subtract a.center a.to in
            let angle = angleFrom + t * (angleTo - angleFrom) in
            Point.add a.center (Point.fromPolar a.r angle)

middle : Curve -> Point
middle q =
    case q of
        CurveBezier b -> Bez.middle b
        CurveArc a -> point q 0.5